name: Version CI

on:
  push:
    branches:
      - master

jobs:
  version-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install balena-cli
      run: |
        sudo apt-get update 
        sudo apt-get install -y curl git python g++ make
        sudo npm install balena-cli -g --production --unsafe-perm
    - name: Run balena cli raspberry pi 2
      run: balena build --deviceType raspberry-pi2 --arch armv7hf --emulated .
    - name: Run balena cli raspberry pi 3
      run: balena build --deviceType raspberrypi3 --arch armv7hf --emulated .
    - name: Run balena cli raspberry pi 3 64
      run: balena build --deviceType raspberrypi3-64 --arch aarch64 --emulated .
    - name: Run balena cli raspberry pi 4
      run: balena build --deviceType raspberrypi4-64 --arch aarch64 --emulated .
