name: Version CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install balena-versionist
      run: |
        sudo npm install -g versionist
        sudo npm install -g balena-versionist
    - name: Run balena-versionist
      run: balena-versionist
    - name: Commit files
      run: |
        git add .
        git config --local user.email "$github_email"
        git config --local user.name "AlexProgrammerDE"
        sudo git commit -m "Update Changelog" -a
      env:
        github_email: ${{ secrets.GITHUB_EMAIL }}
    - name: Create tag
      run: |
        VERSION=$(<VERSION)
        git tag -a v$VERSION -m "Version $VERSION"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
